pr:
  - main

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0

- pwsh: |
    git config --global user.email "AzureDevOps@AzureDevOps.com"
    git config --global user.name "Azure DevOps Build Service"

    $authConfig = git config --list | Select-String "AUTHORIZATION:"
    $url, $authType, $token = $authConfig -Split ' '
    git config --global http.https://github.com.extraheader "AUTHORIZATION: basic $token"
    Write-Host "##vso[task.setvariable variable=gitHubToken;]$token"
  displayName: Set Git Credentials

- pwsh: |
    $pat = $(gitHubToken)
    $orgName = "Sucden-Financial-Limited"
    $base64AuthValue = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f "", $pat)))
    $headers = @{ "Authorization" = ("Basic {0}" -f $base64AuthValue) }
    $apiUrl = "https://api.github.com/repos/Sucden-Financial-Limited/terraform-module-nsg/pull_requests/$(System.PullRequest.PullRequestId)/labels
    $response = Invoke-RestMethod -Uri $apiUrl -Headers $headers
    $response